In [2]:
import numpy as np
import pandas as pd

In [8]:
N = 300000

In [11]:
lines = list()
with open("500000-lines.txt", "r") as fr:
    a = fr.readline()
    for i in range(N):
        lines.append(a)
        a = fr.readline()


In [10]:
with open(f"{N}-lines.txt", "w") as fr:
    for i in range(N):
        fr.write(lines[i])


In [6]:
#lines

In [7]:
for i,line in enumerate(lines):
    lines[i] = line.removesuffix('\n')
#lines

In [231]:
lines

['Tempo de Entrega Até 2 dias após confirmação de pagamento',
 '1. O prazo de validade para a utilização do Vale Presente é de 03 meses (Três meses) a contar da data de sua compra, que constará do e-mail enviado pela Loja Soma de Dois, ao cliente após a confirmação do pagamento.',
 '2. O Vale Presente consiste num código que será enviado ao cliente por e-mail, de acordo com seu cadastro no site da Loja Soma de Dois (https://somadedois.com.br), indicando o valor, a data da compra, o código que deverá ser utilizado e o link relativo a este regulamento de utilização.',
 '3. O valor do Vale Presente pode ser utilizado para quaisquer compras de produtos no site da Loja Soma de Dois (https://somadedois.com.br).',
 '5. Utilização “passo-a-passo” do Vale Presente:',
 '· visite o site da Loja Soma de Dois;',
 '· na página do carrinho de compras, verifique os produtos que escolheu, inclua seu CEP para a entrega, e o código constante do Vale Presente.',
 '6. Após o período de validade do Vale Pre

In [232]:
all_words = ' '.join(lines)

In [233]:
all_words[:400]

'Tempo de Entrega Até 2 dias após confirmação de pagamento 1. O prazo de validade para a utilização do Vale Presente é de 03 meses (Três meses) a contar da data de sua compra, que constará do e-mail enviado pela Loja Soma de Dois, ao cliente após a confirmação do pagamento. 2. O Vale Presente consiste num código que será enviado ao cliente por e-mail, de acordo com seu cadastro no site da Loja Soma'

In [234]:
#all_words

In [235]:
puncts = ['.', ',', ';', ':', '!', '?', '"', '\'', '\\', '-', '_', '+', '$', '*', '´', '`', '~', '^', 'º', 'ª', '«', '»', '<', '>']
for punct in puncts:
    all_words = all_words.replace(punct, ' ' + punct)#.split(' ')
all_words = all_words.split(' ')

In [236]:
all_words[:400]

['Tempo',
 'de',
 'Entrega',
 'Até',
 '2',
 'dias',
 'após',
 'confirmação',
 'de',
 'pagamento',
 '1',
 '.',
 'O',
 'prazo',
 'de',
 'validade',
 'para',
 'a',
 'utilização',
 'do',
 'Vale',
 'Presente',
 'é',
 'de',
 '03',
 'meses',
 '(Três',
 'meses)',
 'a',
 'contar',
 'da',
 'data',
 'de',
 'sua',
 'compra',
 ',',
 'que',
 'constará',
 'do',
 'e',
 '-mail',
 'enviado',
 'pela',
 'Loja',
 'Soma',
 'de',
 'Dois',
 ',',
 'ao',
 'cliente',
 'após',
 'a',
 'confirmação',
 'do',
 'pagamento',
 '.',
 '2',
 '.',
 'O',
 'Vale',
 'Presente',
 'consiste',
 'num',
 'código',
 'que',
 'será',
 'enviado',
 'ao',
 'cliente',
 'por',
 'e',
 '-mail',
 ',',
 'de',
 'acordo',
 'com',
 'seu',
 'cadastro',
 'no',
 'site',
 'da',
 'Loja',
 'Soma',
 'de',
 'Dois',
 '(https',
 '://somadedois',
 '.com',
 '.br)',
 ',',
 'indicando',
 'o',
 'valor',
 ',',
 'a',
 'data',
 'da',
 'compra',
 ',',
 'o',
 'código',
 'que',
 'deverá',
 'ser',
 'utilizado',
 'e',
 'o',
 'link',
 'relativo',
 'a',
 'este',
 'regula

In [237]:
all_words = [x.lower()  for x in all_words if ((x != ' ') and (x != '') and not x.isnumeric() )]

In [238]:
all_words

['tempo',
 'de',
 'entrega',
 'até',
 'dias',
 'após',
 'confirmação',
 'de',
 'pagamento',
 '.',
 'o',
 'prazo',
 'de',
 'validade',
 'para',
 'a',
 'utilização',
 'do',
 'vale',
 'presente',
 'é',
 'de',
 'meses',
 '(três',
 'meses)',
 'a',
 'contar',
 'da',
 'data',
 'de',
 'sua',
 'compra',
 ',',
 'que',
 'constará',
 'do',
 'e',
 '-mail',
 'enviado',
 'pela',
 'loja',
 'soma',
 'de',
 'dois',
 ',',
 'ao',
 'cliente',
 'após',
 'a',
 'confirmação',
 'do',
 'pagamento',
 '.',
 '.',
 'o',
 'vale',
 'presente',
 'consiste',
 'num',
 'código',
 'que',
 'será',
 'enviado',
 'ao',
 'cliente',
 'por',
 'e',
 '-mail',
 ',',
 'de',
 'acordo',
 'com',
 'seu',
 'cadastro',
 'no',
 'site',
 'da',
 'loja',
 'soma',
 'de',
 'dois',
 '(https',
 '://somadedois',
 '.com',
 '.br)',
 ',',
 'indicando',
 'o',
 'valor',
 ',',
 'a',
 'data',
 'da',
 'compra',
 ',',
 'o',
 'código',
 'que',
 'deverá',
 'ser',
 'utilizado',
 'e',
 'o',
 'link',
 'relativo',
 'a',
 'este',
 'regulamento',
 'de',
 'utilizaç

In [239]:
min_freq = 10

In [240]:
relevant_words = pd.Series(all_words).value_counts()[pd.Series(all_words).value_counts() > min_freq]

In [241]:
dict_len = relevant_words.size

In [242]:
indices = pd.DataFrame(relevant_words).reset_index()[['index']].reset_index().iloc[:,0]
words = pd.DataFrame(relevant_words).reset_index()[['index']].reset_index().iloc[:,1]

In [243]:
ind_to_words_dict = dict(zip(indices, words))
#ind_to_words_dict

In [244]:
words_to_ind_dict = dict(zip(words, indices))
#words_to_ind_dict

In [245]:
dict_len = len(list(words_to_ind_dict.keys()))

In [246]:
dict_len

32080

In [247]:
window_size = 8
CO_matrix = np.zeros((dict_len,dict_len))

for i in range(window_size//2, len(all_words)-(window_size//2)):
    if(all_words[i] in words_to_ind_dict.keys()):
        curr_word = all_words[i]
        for k in range(-(window_size//2), (window_size//2)+1):
            if (all_words[i+k] in words_to_ind_dict.keys()):
                ind_curr_word = words_to_ind_dict[curr_word]
                if k < 0:
                    a = (window_size//2)+1 + k
                    CO_matrix[ind_curr_word][words_to_ind_dict[all_words[i+k]]] += a
                elif k > 0:
                    a = (window_size//2)+1 - k
                    CO_matrix[words_to_ind_dict[all_words[i+k]]][ind_curr_word] += a

CO_matrix


array([[4.38800e+05, 2.24104e+05, 3.86446e+05, ..., 1.60000e+01,
        0.00000e+00, 2.80000e+01],
       [1.39834e+05, 4.95166e+05, 2.80186e+05, ..., 1.00000e+01,
        0.00000e+00, 1.40000e+01],
       [2.79180e+05, 1.64348e+05, 2.26296e+05, ..., 0.00000e+00,
        1.20000e+01, 8.00000e+00],
       ...,
       [2.20000e+01, 4.00000e+00, 6.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [3.40000e+01, 2.20000e+01, 2.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [0.00000e+00, 4.00000e+00, 1.20000e+01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [248]:
word1 = 'bonito'
word2 = 'bonita'

In [249]:
CO_matrix[words_to_ind_dict[word1]]/CO_matrix[words_to_ind_dict[word1]].sum()

array([0.04431347, 0.02379393, 0.03274394, ..., 0.        , 0.        ,
       0.        ])

In [250]:
CO_matrix[words_to_ind_dict[word2]]/CO_matrix[words_to_ind_dict[word2]].sum()

array([0.04893065, 0.02754375, 0.01814647, ..., 0.        , 0.        ,
       0.        ])

In [251]:
diff_vec = abs(CO_matrix[words_to_ind_dict[word1]]/CO_matrix[words_to_ind_dict[word1]].sum() - CO_matrix[words_to_ind_dict[word2]]/CO_matrix[words_to_ind_dict[word2]].sum())

In [252]:
diff_vec.sum()

1.035695919478055

In [268]:
word1 = 'sabedoria'
#word2 = 'bonita'

In [269]:
diffs = list()
for word2 in list(words_to_ind_dict.keys()):
    diff_vec = abs(CO_matrix[words_to_ind_dict[word1]]/CO_matrix[words_to_ind_dict[word1]].sum() - CO_matrix[words_to_ind_dict[word2]]/CO_matrix[words_to_ind_dict[word2]].sum()).sum()
    diffs.append(diff_vec)
best_ws = sorted(list(enumerate(diffs)), key=lambda x: x[1])


In [270]:
#best_ws

In [271]:
#best_ws[:10]

In [272]:
[list(words_to_ind_dict.keys())[x[0]] for x in best_ws[:10]]

['sabedoria',
 'força',
 'fé',
 'liberdade',
 'paixão',
 'alegria',
 'personalidade',
 'capacidade',
 'riqueza',
 'poesia']